name: Python Tests with Coverage (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run setup.bat (Windows version)
        run: setup.bat
        shell: cmd

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r tests/requirements.txt
        shell: cmd

      - name: Configure environment paths
        run: |
          echo "PATH=${{ github.workspace }}\\ext\\blender;${{ github.workspace }}\\USD\\windows\\lib\\python;${{ github.workspace }}\\USD\\windows\\plugin\\usd;$env:PATH" >> $env:GITHUB_ENV
          echo "PYTHONPATH=${{ github.workspace }}\\USD\\windows\\lib\\python;${{ github.workspace }}\\src" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Run tests with coverage
        run: |
          echo "PATH is: $env:PATH"
          echo "PYTHONPATH is: $env:PYTHONPATH"
          pytest -v --cov --cov-branch --cov-report=term --cov-report=xml tests/
        shell: pwsh

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
