name: Ubuntu 22.04

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run setup.sh
        run: chmod +x setup.sh && ./setup.sh

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r tests/requirements.txt

      - name: Test multiverse_parser
        run: scripts/multiverse_parser --help

      - name: Configure environment paths
        run: |
          echo "PATH=$PWD/ext/blender:$PWD/USD/linux/lib/python:$PWD/USD/linux/plugin/usd:$PATH" >> $GITHUB_ENV
          echo "PYTHONPATH=$PWD/USD/linux/lib/python:$PWD/src" >> $GITHUB_ENV

      - name: Run tests with coverage
        run: |
          echo "PATH is: $PATH"
          echo "PYTHONPATH is: $PYTHONPATH"
          PATH=$PATH PYTHONPATH=$PYTHONPATH pytest -v --cov=src --cov-branch --cov-report=term --cov-report=xml tests/

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
