name: Python Tests with Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r tests/requirements.txt

      - name: Configure environment paths
        run: |
          echo "PATH=$PWD/ext/blender:$PWD/USD/linux/lib/python:$PWD/USD/linux/plugin/usd:$PATH" >> $GITHUB_ENV
          echo "PYTHONPATH=$PWD/linux/lib/python:$PWD/src" >> $GITHUB_ENV

      - name: Run tests with coverage
        run: |
          echo $PATH
          echo $PYTHONPATH
          coverage run -m pytest tests/
          coverage report
          coverage xml  # generate coverage.xml for Codecov

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
